[phases.setup]
nixPkgs = [
    "...",
    "nodejs_22",
    "pnpm"
]

[phases.build]
cmds = [
    "pnpm install",
    "pnpm run build",
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"